tools/multiqc.wdl
workflows/star-qc.wdl
workflows/start-to-finish.wdl

Addresses feedback on the RFC from Kyle regarding duplicate marking. Removing that step and updating the downstream steps to use the STAR aligned BAM directly.

Removing Picard MarkDuplicates step

---

workflows/interactive-tsne/inputs/defaults.json
workflows/interactive-tsne/inputs/defaults_bam.json
workflows/interactive-tsne/inputs/defaults_counts.json
workflows/interactive-tsne/inputs/extras.json
workflows/interactive-tsne/interactive_tsne_from_bams.wdl
workflows/interactive-tsne/interactive_tsne_from_counts.wdl

Adding a pipeline to take aligned BAM input (must be GRCh38) and run the t-SNE plot code combined with our reference data.
Adding a second pipeline to take htseq-count output and run the t-SNE plot code.

Adding abbreviated t-SNE pipelines based on aligned BAM or htseq-count inputs

---

tools/deeptools.wdl
tools/samtools.wdl
tools/star.wdl
workflows/general/bam-to-fastqs.wdl
workflows/rnaseq/rnaseq-standard.wdl
workflows/rnaseq_expression_classification/rnaseq_expression_classification.wdl

In cloud environments, STAR defaulted to 1 core despite the instance having multiple cores to satisfy the memory requirement. This changes the threading of STAR to use all available cores, unless the number of CPUs was explicitly passed.

Changing STAR alignment to use either the number of cores if specified or all available cores

---

tools/samtools.wdl

While running my CI RNA-Seq job on staging, I got an error while running the workflow. I thought it was something I did because I was changing how the pod was running the workflow, but on looking further it was `samtools index` erroring due to an invalid option.
This was the logs:
```
index: invalid option -- '-'
Usage: samtools index [-bc] [-m INT] <in.bam> [out.index]
Options:
-b       Generate BAI-format index for BAM files [default]
-c       Generate CSI-format index for BAM files
-m INT   Set minimum interval size for CSI indices to 2^INT [14]
-@ INT   Sets the number of threads [none]
```
I've updated the workflow with the expected flag, but I thought this was a good case of the CI picking up an error (albeit after it was merged).

fix: changed samtools index threads option

---

tools/htseq.wdl

Changing HTSeq file output suffix to *.feature-counts.txt to match existing St. Jude Cloud feature count file format

HTSeq output rename

---

tools/multiqc.wdl
tools/samtools.wdl
workflows/qc/quality-check-standard.wdl

For large BAMs `picard validate` can take multiple hours, preventing any other tools from running. This adds `samtools quickcheck` to do a precursory validation before other tools run as opposed to waiting for the complete `picard validate`.

refactor: use samtools quickcheck to do initial validation

---

tools/bwa.wdl
tools/fq.wdl
tools/star.wdl
workflows/chipseq/chipseq-bwa-db-build.wdl
workflows/chipseq/chipseq-standard.wdl
workflows/general/bwa-db-build.wdl
workflows/rnaseq/rnaseq-star-db-build.wdl

To support a user, we want to be able to use rnaseq-standard-fastq with dxCompiler. dxCompiler sets stricter requirements than miniwdl or cromwell. This PR addresses those requirements.

Update WDL tasks to comply with dxCompiler restrictions

---

workflows/chipseq/chipseq-standard.wdl

The util WDL script was renamed in the SEAseq repository. This PR renames it in our import to match.

Updated SEAseq util path to reflect change in the SEAseq repo

---

workflows/chipseq/chipseq-standard.wdl
workflows/rnaseq/rnaseq-standard-fastq.wdl
workflows/rnaseq/rnaseq-standard.wdl
workflows/scrnaseq/scrnaseq-standard.wdl

During a discussion about how QC calculates and outputs an MD5 sum that's never used by our broader pipelines, me and @adthrasher agreed that *all* our WDL workflows should be producing MD5 sums and we should be validating them at various points. This change sets us up to be more proactive about detecting corruption (the next step would be actually using these MD5s).

feat: compute and output md5 checksum for all BAM alignment workflows

---

tools/bwa.wdl
tools/fq.wdl
tools/kraken.wdl
workflows/general/bam-to-fastqs.wdl
workflows/qc/quality-check-standard.wdl
workflows/rnaseq/rnaseq-standard-fastq.wdl
workflows/scrnaseq/10x-bam-to-fastqs.wdl

In addition to exposing `fq lint` options, there are 2 other minor changes.
1) All `read_*_fastq_gz` input variables to `fq` tasks have had the `_gz` suffix dropped. `fq` accepts raw input as well, and auto detects which the file is.
2) The `basename()` regex for FASTQ files that is used in multiple files has been updated to catch lowercase `_r1`/`_r2` extensions.

feat(fq): expose lint options

---

tools/bwa.wdl
tools/samtools.wdl
workflows/dnaseq/dnaseq-standard.wdl
workflows/rnaseq/rnaseq-standard.wdl

This PR has a few changes alongside the dnaseq-standard experimental WF.
* fix: `get_read_group` usage in rnaseq-standard
* feat: read2 support in bwa-mem
* style: split FASTQs naming went from `<sample>_<read group>_R<1/2>.fastq` to `<sample>.<read group>.R<1/2>.fastq`

feat: experimental dnaseq-standard WF

---

README.md

title. As stated in Slack, I am opting to err on the side of understating VS overstating. IMO the goal should be to remove all the bad info (✅ ) and fill back in the bare minimum needed for the README to not be embarrassing.
IMO we remove the whole `conf` and `bin` directories, but I didn't pull the trigger on that yet.

docs: gut the README of outdated information. Fill back in sparsely.

---

tests/tools/test_librarian.yaml
tools/librarian.wdl
tools/multiqc.wdl
workflows/qc/inputs/multiqc_config_hg38.yaml
workflows/qc/quality-check-standard.wdl
workflows/rnaseq/rnaseq-standard-fastq.wdl
workflows/rnaseq/rnaseq-standard.wdl
workflows/scrnaseq/10x-bam-to-fastqs.wdl

The `librarian` tool is still under development (see https://github.com/DesmondWillowbrook/Librarian/issues/17), but there are passenger-changes I added to this branch I want to see in `main`. So I'm voting for a preemptive merge, and we can update `librarian` later.
The passenger change in question: changing how analyses are toggled on/off in QC. By this, I mean we now present a "base set of analyses" with a number of "extra analyses" that can be **toggled on**, but are **off by default**. This is more-or-less how it currently works, though we had a variety of "toggling methods" and it was awkward IMO.
In practice, the above means dropping the `"DNA"/"RNA"` `String molecule` parameter and replacing it with `Boolean rna = false`. And some tweaking of phrasing in the docs.

feat: librarian

---

tools/picard.wdl

^Tiitle
Brought to my attention by a user with files that were failing during Picard steps due to a MAPQ>0 for unmapped reads. This should fix that.

fix(tools/picard): make VALIDATION_STRINGENCY SILENT the default

---

tests/tools/test_picard.py
tests/tools/test_picard.yaml
tools/picard.wdl

For non-coordinate sorts, `picard SortSam` does not output a BAM index, even if `CREATE_INDEX` is `true`. This puts an existence check around the rename of the BAI file and also makes the output bam_index an optional output. Fortunately, it appears that we are not using the generated index in any of our pipelines as something always consumes and transforms the BAM downstream, so it ends up reindexed.
Resolves #155

fix: make index optional

---

.github/workflows/sprocket-check.yaml
.github/workflows/sprocket-lint.yaml

Switch to the public Sprocket action instead of installing Rust and Sprocket on the runner manually.

ci: use public Sprocket action

---

.github/workflows/docker-build.yaml
.github/workflows/docker-clean.yaml

- The `gh` CLI tool needs to token to be present in the environment to authenticate.
- Updated the digest check for the locally built image for the comparison check.
- Checks out the repo for the delete step since it needs to read the `package.json` files.
- Fixes a bug in the `jq` filtering of docker images.

fix: add token to environment for gh cli, jq query update, digest comparison update

---

.github/workflows/build-and-test.yaml
.github/workflows/docker-build.yaml
.github/workflows/pytest.yaml

Fixes the CI for the hundredth time this week (and hopefully the last time).

ci: build and test

---

.github/workflows/validate-inputs.yaml

Add CI for validating our reference input JSONs.

ci: Create validate-inputs.yaml

---

developer_scripts/update_container_tags.sh

With the previous solution, the bash argument wasn't being interpreted by the Mac `sed` version as a zero-length string. So it was appending the literal `''` suffix and creating backup files. The fix is repetitive, but I can't get anything else to recognize the zero-length string properly.

fix: backup extension on mac works now

---

tools/samtools.wdl

The declaration of the `struct` is incorrect. It worked, because the object could be coerced to a struct type.

fix: correct struct declaration

---

.github/workflows/sprocket-lint.yaml
requirements-dev.txt
tools/arriba.wdl
tools/fq.wdl
tools/gatk4.wdl
tools/htseq.wdl
tools/kraken2.wdl
tools/picard.wdl
tools/samtools.wdl
tools/util.wdl
workflows/dnaseq/dnaseq-core.wdl
workflows/dnaseq/dnaseq-standard-fastq.wdl
workflows/dnaseq/dnaseq-standard.wdl
workflows/general/alignment-post.wdl
workflows/reference/qc-reference.wdl
workflows/rnaseq/rnaseq-core.wdl
workflows/rnaseq/rnaseq-standard-fastq.wdl
workflows/rnaseq/rnaseq-standard.wdl

Enabling the `TrailingCommas` lint now that `miniwdl` supports the syntax. Updating the WDL files to use trailing commas.

chore: add trailing commas

---

docker/minfi/package.json
scripts/CHANGELOG.md
scripts/methylation/methylation-preprocess.R
workflows/methylation/CHANGELOG.md
workflows/methylation/methylation-preprocess.wdl

When a single-column dataframe is manipulated in R, R silently converts it to a vector. This PR adds `drop = FALSE` to the dataframe manipulation to prevent the conversion.

fix: methylation samplenames
