stjudecloud/workflows

tools/deeptools.wdl, tools/fastqc.wdl, tools/fq.wdl, tools/gzip.wdl, tools/htseq.wdl, tools/md5sum.wdl, tools/multiqc.wdl, tools/picard.wdl, tools/qc.wdl, tools/qualimap.wdl, tools/rseqc.wdl, tools/samtools.wdl, tools/star.wdl, tools/util.wdl, tools/wget.wdl
Adding WDL-style documentation in the parameter_meta and meta fields.
=> Documentation

tools/multiqc.wdl, tools/ngsderive.wdl, tools/qc.wdl, tools/samtools.wdl, workflows/rnaseq/rnaseq-standard.wdl
Fix all suggestions from [MiniWDL](https://github.com/chanzuckerberg/miniwdl). Sidenote, this linter seems much better than `womtool` IMO (caught at least 3 _errors_ that `womtool` didn't).
=> improvement: fix all `miniwdl check` suggestions

conf/lsf.conf, tools/deeptools.wdl, tools/fastqc.wdl, tools/fq.wdl, tools/gzip.wdl, tools/htseq.wdl, tools/md5sum.wdl, tools/multiqc.wdl, tools/picard.wdl, tools/qc.wdl, tools/qualimap.wdl, tools/rseqc.wdl, tools/samtools.wdl, tools/star.wdl, tools/util.wdl, tools/wget.wdl, workflows/general/bam-to-fastqs.wdl, workflows/rnaseq/inputs/rnaseq-standard-inputs.json, workflows/rnaseq/rnaseq-standard.wdl, workflows/rnaseq/rnaseq-star-db-build.wdl
Appreciate any comments or suggestions to improve the workflows based on running these workflows in practice. This is still a WIP right now, but I wanted to get as many improvements in front of people to get their feedback. 
**Changes made:**
- LSF config file
=> Overall Improvements to the workflows

docs/build_for_dnanexus.md, tools/ngsderive.wdl, tools/tsne.wdl, workflows/interactive-tsne/inputs/defaults.json, workflows/interactive-tsne/inputs/defaults_bam.json, workflows/interactive-tsne/inputs/defaults_counts.json, workflows/interactive-tsne/interactive-tsne.wdl, workflows/interactive-tsne/interactive_tsne_from_bams.wdl, workflows/interactive-tsne/interactive_tsne_from_counts.wdl
Updating to match new t-SNE code.
Adding build with dxWDL documentation.
Adding option to save data matrix for t-SNE.
Switching to an archive of counts as input, rather than array of files.
=> Tsne updates

README.md, bin/check-job-alive, conf/lsf.conf
Adding check-job-alive script to return proper information from LSF to Cromwell about job status.
=> Replacing lsf.conf with known good version using ${} syntax. 

tools/htseq.wdl, tools/picard.wdl, workflows/rnaseq/rnaseq-standard.wdl, workflows/rnaseq_expression_classification/rnaseq_expression_classification.wdl, workflows/rnaseq_expression_classification/rnaseq_expression_classification_from_bams.wdl
Make htseq memory configurable. Output Picard ValidateSam errors.
=> Expression updates

.github/workflows/lint-check.yml, tools/bwa.wdl, workflows/general/bwa-db-build.wdl, workflows/rnaseq/rnaseq-standard-fastq.wdl, workflows/rnaseq/rnaseq-standard.wdl
Adding optional step to run XenoCP on sample after the initial alignment
=> Add xenograft cleansing support for RNA-Seq V2

tools/htseq.wdl, workflows/rnaseq/rnaseq-standard.wdl
=> fix(htseq): add arbitrarily large number to max-reads-in-buffer

.github/workflows/docker-branch.yml, .github/workflows/docker-master.yml, docker/cellranger/1.0.0/Dockerfile, docker/fqlib/1.1.0/Dockerfile, tools/cellranger.wdl, workflows/scrnaseq/10x-bam-to-fastqs.wdl, workflows/scrnaseq/scrnaseq-standard.wdl
Implementation of pipeline described by https://github.com/stjudecloud/rfcs/blob/rfcs/scrnaseq/text/0002-scRNA-Seq-workflow.md
=> Initial draft of Cell Ranger-based scRNA-Seq workflow.

.github/workflows/cd.yml, .github/workflows/docker-branch.yml, .github/workflows/docker-master.yml, .github/workflows/lint-check.yml, .github/workflows/miniwdl-check.yml
Adds repository name to workflows for external observability.
=> ci: updates action names for external observability

docker/util/1.3.0/Dockerfile, tools/bwa.wdl, tools/estimate.wdl, tools/md5sum.wdl, tools/ngsderive.wdl, tools/util.wdl, workflows/qc/quality-check-standard.wdl, workflows/rnaseq/rnaseq-standard.wdl, workflows/scrnaseq/10x-bam-to-fastqs.wdl
Adds a task/script that computes a variety of metrics about PHRED scores across the BAM. These are not currently incorporated into the per-sample MultiQC reports. That integration is waiting on the MultiQC task overhaul I have planned.
=> feat(qc): Global Phred scores

tools/util.wdl
=> feat: calc PHRED stats for first and last base in all reads

best-practices.md, style-guide.md, template/task-templates.wdl, tests/tools/test_estimate.yaml, tools/bwa.wdl, tools/cellranger.wdl, tools/deeptools.wdl, tools/estimate.wdl, tools/fastqc.wdl, tools/fq.wdl, tools/htseq.wdl, tools/kraken2.wdl, tools/md5sum.wdl, tools/mosdepth.wdl, tools/multiqc.wdl, tools/ngsderive.wdl, tools/picard.wdl, tools/qualimap.wdl, tools/samtools.wdl, tools/star.wdl, tools/util.wdl, workflows/qc/quality-check-standard.wdl, workflows/rnaseq/ESTIMATE.wdl, workflows/rnaseq/rnaseq-standard-fastq.wdl, workflows/rnaseq/rnaseq-standard.wdl, workflows/scrnaseq/10x-bam-to-fastqs.wdl
Please feel free to nitpick over language etc. Hoping for this to be the "final" version of the style-guide and best-practices docs before we go live.
=> docs: new stuff for style-guide, best-practices, and template

tools/samtools.wdl
Samtools changes split off from PR #111
=> chore: move from pr #111

tools/util.wdl
=> fix(util/global_phred_scores): include soft clipped bases

.github/workflows/sprocket-lint.yaml, tools/cellranger.wdl, tools/picard.wdl, tools/qualimap.wdl, tools/samtools.wdl, tools/util.wdl, workflows/dnaseq/dnaseq-standard.wdl, workflows/scrnaseq/10x-bam-to-fastqs.wdl
=> Sprocket lint

tools/util.wdl
Update util docker image version for consistency.
=> chore: Bump util version

workflows/dnaseq/dnaseq-standard.wdl
Of course, I missed a single record.
=> chore: single -> double quotes

tools/gatk4.wdl, tools/picard.wdl, workflows/dnaseq/dnaseq-core.wdl, workflows/dnaseq/dnaseq-standard-fastq.wdl, workflows/dnaseq/dnaseq-standard.wdl, workflows/general/samtools-merge.wdl, workflows/reference/gatk-reference.wdl, workflows/reference/make-qc-reference.wdl, workflows/rnaseq/rnaseq-variant-calling.wdl
Reorder inputs to satisfy the lint rules. Plus one import sort change.
=> chore: apply changes for lint

data_structures/CHANGELOG.md, tools/CHANGELOG.md, workflows/chipseq/CHANGELOG.md, workflows/dnaseq/CHANGELOG.md, workflows/general/CHANGELOG.md, workflows/qc/CHANGELOG.md, workflows/reference/CHANGELOG.md, workflows/rnaseq/CHANGELOG.md
Self-explanatory. The hard part is going to be getting into the practice of updating these as part of every PR.
=> chore: add blank CHANGELOGs

.github/pull_request_template.md, data_structures/CHANGELOG.md, tools/CHANGELOG.md, workflows/chipseq/CHANGELOG.md, workflows/dnaseq/CHANGELOG.md, workflows/general/CHANGELOG.md, workflows/qc/CHANGELOG.md, workflows/reference/CHANGELOG.md, workflows/rnaseq/CHANGELOG.md
I created a bunch of blank CHANGELOGs for us to start using and I don't think we've added a single entry to any of them 😬 
Hopefully this PR template will remind us to start filling those in.
=> docs: Create pull_request_template.md

.github/workflows/docker-clean.yaml
Name the docker image deletion action.
Update the call to `delete-package-versions` to correctly pass the package information.
=> fix: package deletion

.github/workflows/sprocket-lint.yaml, .github/workflows/validate-inputs.yaml, data_structures/flag_filter.wdl, data_structures/read_group.wdl, docker/util/package.json, tools/htseq.wdl, tools/kraken2.wdl, tools/md5sum.wdl, tools/picard.wdl, tools/qualimap.wdl, tools/samtools.wdl, tools/util.wdl, workflows/dnaseq/dnaseq-standard-fastq.wdl, workflows/dnaseq/dnaseq-standard.wdl, workflows/qc/quality-check-standard.wdl, workflows/rnaseq/rnaseq-standard.wdl
=> fix: updates to sprocket CI

.gitignore, tools/util.wdl
=> fix: fixes check_fq_and_rg_concordance

data_structures/flag_filter.wdl, data_structures/read_group.wdl, docker/python-plotting/package.json, docker/umap/package.json, docker/util/package.json, tools/bwa.wdl, tools/htseq.wdl, tools/md5sum.wdl, tools/samtools.wdl, tools/util.wdl, workflows/dnaseq/dnaseq-standard.wdl, workflows/methylation/methylation-cohort.wdl, workflows/qc/quality-check-standard.wdl, workflows/rnaseq/rnaseq-standard.wdl
noticed while working on #251 that we had left work dirs polluted with symlinks. This PR just adds some `rm` statements to clean up after ourselves.
=> chore: clean up symlinks after execution

.github/pull_request_template.md, .github/workflows/sprocket-check.yaml, .github/workflows/sprocket-lint.yaml, .gitignore, .sprocketignore, sprocket.toml, tools/CHANGELOG.md, tools/bwa.wdl, tools/star.wdl
Fixes CI to reflect the latest sprocket-action release and does some missing temp file cleaning steps
=> chore: clean up

data_structures/flag_filter.wdl, data_structures/read_group.wdl, docker/util/package.json, tests/input/README.md, tools/htseq.wdl, tools/md5sum.wdl, tools/util.wdl, workflows/dnaseq/dnaseq-standard.wdl, workflows/qc/quality-check-standard.wdl, workflows/rnaseq/rnaseq-standard.wdl
Adds additional source information for test inputs.
=> docs: add additional source data for test inputs
